name: animation_cheat_page
description: Presentations made with Flutter

environment:
  sdk: ">=2.6.0-dev.0.0.flutter-1103600280 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  presentation: ^0.0.10+1
  google_fonts: ^0.2.0
  http: ^0.12.0+1
  universal_html: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  test: ^1.6.3
  args: ^1.5.2
  process_run: ^0.10.3
  rxdart: 0.22.0
  fast_flutter_driver:
    git:
      url: git://github.com/tomaszpolanski/fast_flutter_driver.git

flutter:

  uses-material-design: true
  assets:
    - assets/favicon.png
    - assets/logo-192.png
    - assets/manifest.json
